### ISSUE TITLE
Can't enable screen lock

### ISSUE THREAD

**Issue by shrugal** [hiwenhu/hisql#1]
I bought the premium version and tried to enable the screen lock feature, but when I flip the switch the following error message is shown:

`local_auth plugin requires activity to be a FragmentActivity`

I tried clearing the cache and restarting the app, but it didn't change anything. This is on a Samsung Galaxy Tab S8 using Android 13 and One UI 5.

**Comment by hiwenhu** [comment]
Hi, shrugal. I have found the reason for the error. I will fix the problem as soon as possible. The next version will solve it.

**Comment by hiwenhu** [comment]
Hi, shrugal. I have found the reason for the error. I will fix the problem
as soon as possible. The next version will solve it.

Shrugal ***@***.***>于2023年2月22日 周三20:18写道：

**Comment by hiwenhu** [comment]
Hi, Shrugal. The problem has been solved. The new version 1.0.4 has been
released on the play store. Please update the app when you have time.
Best regards.

Mk Pan ***@***.***>于2023年2月22日 周三23:02写道：

**Comment by shrugal** [comment]
That did it! Ty very much for the quick fix!
